[2025-07-19T18:09:20.507+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-19T18:09:20.525+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: banking_data_quality.run_monitoring_audit scheduled__2025-07-18T17:00:00+00:00 [queued]>
[2025-07-19T18:09:20.533+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: banking_data_quality.run_monitoring_audit scheduled__2025-07-18T17:00:00+00:00 [queued]>
[2025-07-19T18:09:20.534+0000] {taskinstance.py:2856} INFO - Starting attempt 6 of 7
[2025-07-19T18:09:20.550+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): run_monitoring_audit> on 2025-07-18 17:00:00+00:00
[2025-07-19T18:09:20.559+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-19T18:09:20.561+0000] {standard_task_runner.py:72} INFO - Started process 240 to run task
[2025-07-19T18:09:20.561+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'banking_data_quality', 'run_monitoring_audit', 'scheduled__2025-07-18T17:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/banking_dq_dag.py', '--cfg-path', '/tmp/tmpestczon6']
[2025-07-19T18:09:20.563+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask run_monitoring_audit
[2025-07-19T18:09:20.615+0000] {task_command.py:467} INFO - Running <TaskInstance: banking_data_quality.run_monitoring_audit scheduled__2025-07-18T17:00:00+00:00 [running]> on host 2e145ce6e7b6
[2025-07-19T18:09:20.709+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='banking_data_quality' AIRFLOW_CTX_TASK_ID='run_monitoring_audit' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T17:00:00+00:00'
[2025-07-19T18:09:20.711+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-19T18:09:20.854+0000] {logging_mixin.py:190} INFO - 
Monitoring and Audit Summary:
[2025-07-19T18:09:20.855+0000] {logging_mixin.py:190} INFO - checks = [{'Check': 'High-Value Transaction Auth', 'Status': 'FAIL', 'Details': '61 transactions >10M VND without strong auth'}, {'Check': 'Unverified Device Usage', 'Status': 'FAIL', 'Details': '37 transactions from unverified devices'}, {'Check': 'Daily Transaction Limit Auth', 'Status': 'FAIL', 'Details': '3 customers with >20M VND/day without strong auth'}]
[2025-07-19T18:09:20.855+0000] {logging_mixin.py:190} INFO - Monitoring checks failed: 'NoneType' object is not subscriptable
[2025-07-19T18:09:20.855+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/banking_dq_dag.py", line 53, in run_monitoring_audit_task
    failed_checks = df[df['Status'] == 'FAIL']
                       ~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2025-07-19T18:09:20.870+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=banking_data_quality, task_id=run_monitoring_audit, run_id=scheduled__2025-07-18T17:00:00+00:00, execution_date=20250718T170000, start_date=20250719T180920, end_date=20250719T180920
[2025-07-19T18:09:20.885+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-19T18:09:20.885+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task run_monitoring_audit ('NoneType' object is not subscriptable; 240)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/banking_dq_dag.py", line 53, in run_monitoring_audit_task
    failed_checks = df[df['Status'] == 'FAIL']
                       ~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2025-07-19T18:09:20.935+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-07-19T18:09:20.954+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-19T18:09:20.957+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
